auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /tmp/loki
  storage:
    filesystem:
      directory: /tmp/loki/index

ruler:
  enable: false

limits_config:
  reject_old_samples: false

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem
      schema: v12  # Adjusted for Loki 3.0.0
      index:
        prefix: index_
        period: 168h

